---
- name: Configurar servidores Ubuntu
  hosts: servers
  become: yes
  tasks:
    - name: Actualizar los paquetes del sistema
      apt:
        update_cache: yes
        upgrade: yes

    - name: Crear usuario 'itla'
      user:
        name: itla
        state: present
        create_home: yes

    - name: Crear carpeta 'app'
      file:
        path: /home/itla/app
        state: directory
        owner: itla
        group: itla
        mode: '0755'

    - name: Crear archivo hola.txt
      copy:
        content: "Hola desde Ansible!\n"
        dest: /home/itla/app/hola.txt
        owner: itla
        group: itla
        mode: '0644'

    - name: Instalar cowsay y htop
      apt:
        name:
          - cowsay
          - htop
        state: present
        update_cache: yes

